baseURL = "https://cvidon.com/"
title = "Clément Vidon"
enableRobotsTXT = true
enableGitInfo = true
disableKinds = ["taxonomy", "term"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    locale = "en"
    label = "English"
    weight = 1

  [languages.fr]
    locale = "fr"
    label = "Français"
    weight = 2

[params]
description = "Personal website of Clément Vidon."

[sitemap]
  changefreq = "weekly"
  priority = 0.5
