baseURL = "https://cvidon.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Clément Vidon"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
description = "Personal website of Clément Vidon."

[sitemap]
  changefreq = "weekly"
  priority = 0.5
